name: Build Kernel

on:
  workflow_call:
    inputs:
      include_ksu:
        required: true
        type: string
      kernel_git:
        required: true
        type: string
      kernel_branch:
        required: true
        type: string
      kernel_type:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build-kernel:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Environment
        id: env
        run: |
            echo "Setting up the environment"
            sudo bash env.sh
      - name: Build
        id: build
        run: |
            echo "Building ${{ inputs.include_ksu }}"
            sudo bash main.sh ${{ inputs.include_ksu }} ${{ inputs.kernel_git }} ${{ inputs.kernel_branch }} ${{ inputs.kernel_type }}
      - name: Get Tag
        id: tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          if [[ -z "$latest_tag" ]]; then latest_tag='v0'; fi
          echo "Latest Tag: $latest_tag"
          echo "tag=v$((${latest_tag:1} + 1))" >> $GITHUB_ENV
      - name: Prepare Upload
        id: prepare
        run: |
          cd $GITHUB_WORKSPACE/out
          zip_name="$(ls *.zip)"
          echo "kernel_name=${zip_name::-4}" >> $GITHUB_ENV
          if [[ ! -f name.txt ]]; then
              sudo echo "${{ env.kernel_name }}-${{ env.tag }}" > name.txt
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.kernel_name }}
          path: out/*
